version: "3.8"
services:
    app:
        build: .
        depends_on:
            mysql_db:
                condition: service_healthy
        networks:
            - db_data


    mysql_db:
        container_name: mysql_db
        image: mysql
        environment:
            # change this for a "real" app!
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "root"
            MYSQL_DATABASE: "promethechapps_dafy"
        ports:
            - 3306:3306
        networks:
            - db_data
        volumes:
            - ./input/create.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

networks:
    db_data:
        driver: bridge